// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/:locale?": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/get-involved": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/frequently-asked-questions": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/latest-updates": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/game-worlds": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/game-worlds/create": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/game-worlds/import": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/*": {
    params: {
      "locale"?: string;
      "*": string;
    };
  };
  "/game/:serverSlug/not-allowed": {
    params: {
      "serverSlug": string;
    };
  };
  "/game/:serverSlug/not-found": {
    params: {
      "serverSlug": string;
    };
  };
  "/game/:serverSlug/:villageSlug": {
    params: {
      "serverSlug": string;
      "villageSlug": string;
    };
  };
  "/game/:serverSlug/:villageSlug/resources": {
    params: {
      "serverSlug": string;
      "villageSlug": string;
    };
  };
  "/game/:serverSlug/:villageSlug/village": {
    params: {
      "serverSlug": string;
      "villageSlug": string;
    };
  };
  "/game/:serverSlug/:villageSlug/map": {
    params: {
      "serverSlug": string;
      "villageSlug": string;
    };
  };
  "/game/:serverSlug/:villageSlug/resources/:buildingFieldId": {
    params: {
      "serverSlug": string;
      "villageSlug": string;
      "buildingFieldId": string;
    };
  };
  "/game/:serverSlug/:villageSlug/village/:buildingFieldId": {
    params: {
      "serverSlug": string;
      "villageSlug": string;
      "buildingFieldId": string;
    };
  };
  "/game/:serverSlug/:villageSlug/production-overview": {
    params: {
      "serverSlug": string;
      "villageSlug": string;
    };
  };
  "/game/:serverSlug/:villageSlug/hero": {
    params: {
      "serverSlug": string;
      "villageSlug": string;
    };
  };
  "/game/:serverSlug/:villageSlug/preferences": {
    params: {
      "serverSlug": string;
      "villageSlug": string;
    };
  };
  "/game/:serverSlug/:villageSlug/statistics": {
    params: {
      "serverSlug": string;
      "villageSlug": string;
    };
  };
  "/game/:serverSlug/:villageSlug/overview": {
    params: {
      "serverSlug": string;
      "villageSlug": string;
    };
  };
  "/game/:serverSlug/:villageSlug/quests": {
    params: {
      "serverSlug": string;
      "villageSlug": string;
    };
  };
  "/game/:serverSlug/:villageSlug/reports": {
    params: {
      "serverSlug": string;
      "villageSlug": string;
    };
  };
  "/game/:serverSlug/:villageSlug/reports/:reportId": {
    params: {
      "serverSlug": string;
      "villageSlug": string;
      "reportId": string;
    };
  };
  "/game/:serverSlug/:villageSlug/oasis-bonus-finder": {
    params: {
      "serverSlug": string;
      "villageSlug": string;
    };
  };
  "/game/:serverSlug/:villageSlug/players": {
    params: {
      "serverSlug": string;
      "villageSlug": string;
    };
  };
  "/game/:serverSlug/:villageSlug/players/:playerSlug": {
    params: {
      "serverSlug": string;
      "villageSlug": string;
      "playerSlug": string;
    };
  };
  "/__spa-preload": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/:locale?" | "/:locale?/get-involved" | "/:locale?/frequently-asked-questions" | "/:locale?/latest-updates" | "/:locale?/game-worlds" | "/:locale?/game-worlds/create" | "/:locale?/game-worlds/import" | "/:locale?/*" | "/game/:serverSlug/not-allowed" | "/game/:serverSlug/not-found" | "/game/:serverSlug/:villageSlug" | "/game/:serverSlug/:villageSlug/resources" | "/game/:serverSlug/:villageSlug/village" | "/game/:serverSlug/:villageSlug/map" | "/game/:serverSlug/:villageSlug/resources/:buildingFieldId" | "/game/:serverSlug/:villageSlug/village/:buildingFieldId" | "/game/:serverSlug/:villageSlug/production-overview" | "/game/:serverSlug/:villageSlug/hero" | "/game/:serverSlug/:villageSlug/preferences" | "/game/:serverSlug/:villageSlug/statistics" | "/game/:serverSlug/:villageSlug/overview" | "/game/:serverSlug/:villageSlug/quests" | "/game/:serverSlug/:villageSlug/reports" | "/game/:serverSlug/:villageSlug/reports/:reportId" | "/game/:serverSlug/:villageSlug/oasis-bonus-finder" | "/game/:serverSlug/:villageSlug/players" | "/game/:serverSlug/:villageSlug/players/:playerSlug" | "/__spa-preload";
  };
  "(public)/layout.tsx": {
    id: "(public)/layout";
    page: "/:locale?" | "/:locale?/get-involved" | "/:locale?/frequently-asked-questions" | "/:locale?/latest-updates" | "/:locale?/game-worlds" | "/:locale?/game-worlds/create" | "/:locale?/game-worlds/import" | "/:locale?/*";
  };
  "(public)/(index)/page.tsx": {
    id: "(public)/(index)/page";
    page: "/:locale?";
  };
  "(public)/(get-involved)/page.tsx": {
    id: "(public)/(get-involved)/page";
    page: "/:locale?/get-involved";
  };
  "(public)/(frequently-asked-questions)/page.tsx": {
    id: "(public)/(frequently-asked-questions)/page";
    page: "/:locale?/frequently-asked-questions";
  };
  "(public)/(latest-updates)/page.tsx": {
    id: "(public)/(latest-updates)/page";
    page: "/:locale?/latest-updates";
  };
  "(public)/(game-worlds)/(index)/page.tsx": {
    id: "(public)/(game-worlds)/(index)/page";
    page: "/:locale?/game-worlds";
  };
  "(public)/(game-worlds)/(create)/page.tsx": {
    id: "(public)/(game-worlds)/(create)/page";
    page: "/:locale?/game-worlds/create";
  };
  "(public)/(game-worlds)/(import)/page.tsx": {
    id: "(public)/(game-worlds)/(import)/page";
    page: "/:locale?/game-worlds/import";
  };
  "(public)/(not-found)/page.tsx": {
    id: "(public)/(not-found)/page";
    page: "/:locale?/*";
  };
  "(game)/(not-allowed)/page.tsx": {
    id: "(game)/(not-allowed)/page";
    page: "/game/:serverSlug/not-allowed";
  };
  "(game)/(not-found)/page.tsx": {
    id: "(game)/(not-found)/page";
    page: "/game/:serverSlug/not-found";
  };
  "(game)/(village-slug)/page.tsx": {
    id: "(game)/(village-slug)/page";
    page: "/game/:serverSlug/:villageSlug" | "/game/:serverSlug/:villageSlug/resources" | "/game/:serverSlug/:villageSlug/village" | "/game/:serverSlug/:villageSlug/map" | "/game/:serverSlug/:villageSlug/resources/:buildingFieldId" | "/game/:serverSlug/:villageSlug/village/:buildingFieldId" | "/game/:serverSlug/:villageSlug/production-overview" | "/game/:serverSlug/:villageSlug/hero" | "/game/:serverSlug/:villageSlug/preferences" | "/game/:serverSlug/:villageSlug/statistics" | "/game/:serverSlug/:villageSlug/overview" | "/game/:serverSlug/:villageSlug/quests" | "/game/:serverSlug/:villageSlug/reports" | "/game/:serverSlug/:villageSlug/reports/:reportId" | "/game/:serverSlug/:villageSlug/oasis-bonus-finder" | "/game/:serverSlug/:villageSlug/players" | "/game/:serverSlug/:villageSlug/players/:playerSlug";
  };
  "(game)/layout.tsx": {
    id: "(game)/layout";
    page: "/game/:serverSlug/:villageSlug/resources" | "/game/:serverSlug/:villageSlug/village" | "/game/:serverSlug/:villageSlug/map" | "/game/:serverSlug/:villageSlug/resources/:buildingFieldId" | "/game/:serverSlug/:villageSlug/village/:buildingFieldId" | "/game/:serverSlug/:villageSlug/production-overview" | "/game/:serverSlug/:villageSlug/hero" | "/game/:serverSlug/:villageSlug/preferences" | "/game/:serverSlug/:villageSlug/statistics" | "/game/:serverSlug/:villageSlug/overview" | "/game/:serverSlug/:villageSlug/quests" | "/game/:serverSlug/:villageSlug/reports" | "/game/:serverSlug/:villageSlug/reports/:reportId" | "/game/:serverSlug/:villageSlug/oasis-bonus-finder" | "/game/:serverSlug/:villageSlug/players" | "/game/:serverSlug/:villageSlug/players/:playerSlug";
  };
  "(game)/(village-slug)/layout.tsx": {
    id: "(game)/(village-slug)/layout";
    page: "/game/:serverSlug/:villageSlug/resources" | "/game/:serverSlug/:villageSlug/village" | "/game/:serverSlug/:villageSlug/map" | "/game/:serverSlug/:villageSlug/resources/:buildingFieldId" | "/game/:serverSlug/:villageSlug/village/:buildingFieldId" | "/game/:serverSlug/:villageSlug/production-overview" | "/game/:serverSlug/:villageSlug/hero" | "/game/:serverSlug/:villageSlug/preferences" | "/game/:serverSlug/:villageSlug/statistics" | "/game/:serverSlug/:villageSlug/overview" | "/game/:serverSlug/:villageSlug/quests" | "/game/:serverSlug/:villageSlug/reports" | "/game/:serverSlug/:villageSlug/reports/:reportId" | "/game/:serverSlug/:villageSlug/oasis-bonus-finder" | "/game/:serverSlug/:villageSlug/players" | "/game/:serverSlug/:villageSlug/players/:playerSlug";
  };
  "(game)/(village-slug)/(village)/page.tsx": {
    id: "resources-page";
    page: "/game/:serverSlug/:villageSlug/resources";
  } | {
    id: "village-page";
    page: "/game/:serverSlug/:villageSlug/village";
  };
  "(game)/(village-slug)/(map)/page.tsx": {
    id: "(game)/(village-slug)/(map)/page";
    page: "/game/:serverSlug/:villageSlug/map";
  };
  "(game)/(village-slug)/fixed-width-layout.tsx": {
    id: "(game)/(village-slug)/fixed-width-layout";
    page: "/game/:serverSlug/:villageSlug/resources/:buildingFieldId" | "/game/:serverSlug/:villageSlug/village/:buildingFieldId" | "/game/:serverSlug/:villageSlug/production-overview" | "/game/:serverSlug/:villageSlug/hero" | "/game/:serverSlug/:villageSlug/preferences" | "/game/:serverSlug/:villageSlug/statistics" | "/game/:serverSlug/:villageSlug/overview" | "/game/:serverSlug/:villageSlug/quests" | "/game/:serverSlug/:villageSlug/reports" | "/game/:serverSlug/:villageSlug/reports/:reportId" | "/game/:serverSlug/:villageSlug/oasis-bonus-finder" | "/game/:serverSlug/:villageSlug/players" | "/game/:serverSlug/:villageSlug/players/:playerSlug";
  };
  "(game)/(village-slug)/(village)/(...building-field-id)/page.tsx": {
    id: "resource-building-field-id-page";
    page: "/game/:serverSlug/:villageSlug/resources/:buildingFieldId";
  } | {
    id: "village-building-field-id-page";
    page: "/game/:serverSlug/:villageSlug/village/:buildingFieldId";
  };
  "(game)/(village-slug)/(production-overview)/page.tsx": {
    id: "(game)/(village-slug)/(production-overview)/page";
    page: "/game/:serverSlug/:villageSlug/production-overview";
  };
  "(game)/(village-slug)/(hero)/page.tsx": {
    id: "(game)/(village-slug)/(hero)/page";
    page: "/game/:serverSlug/:villageSlug/hero";
  };
  "(game)/(village-slug)/(preferences)/page.tsx": {
    id: "(game)/(village-slug)/(preferences)/page";
    page: "/game/:serverSlug/:villageSlug/preferences";
  };
  "(game)/(village-slug)/(statistics)/page.tsx": {
    id: "(game)/(village-slug)/(statistics)/page";
    page: "/game/:serverSlug/:villageSlug/statistics";
  };
  "(game)/(village-slug)/(overview)/page.tsx": {
    id: "(game)/(village-slug)/(overview)/page";
    page: "/game/:serverSlug/:villageSlug/overview";
  };
  "(game)/(village-slug)/(quests)/page.tsx": {
    id: "(game)/(village-slug)/(quests)/page";
    page: "/game/:serverSlug/:villageSlug/quests";
  };
  "(game)/(village-slug)/(reports)/page.tsx": {
    id: "(game)/(village-slug)/(reports)/page";
    page: "/game/:serverSlug/:villageSlug/reports";
  };
  "(game)/(village-slug)/(reports)/(...report-id)/page.tsx": {
    id: "(game)/(village-slug)/(reports)/(...report-id)/page";
    page: "/game/:serverSlug/:villageSlug/reports/:reportId";
  };
  "(game)/(village-slug)/(oasis-bonus-finder)/page.tsx": {
    id: "(game)/(village-slug)/(oasis-bonus-finder)/page";
    page: "/game/:serverSlug/:villageSlug/oasis-bonus-finder";
  };
  "(game)/(village-slug)/(players)/page.tsx": {
    id: "(game)/(village-slug)/(players)/page";
    page: "/game/:serverSlug/:villageSlug/players";
  };
  "(game)/(village-slug)/(players)/(...player-slug)/page.tsx": {
    id: "(game)/(village-slug)/(players)/(...player-slug)/page";
    page: "/game/:serverSlug/:villageSlug/players/:playerSlug";
  };
  "(internal)/(spa-preload)/page.tsx": {
    id: "(internal)/(spa-preload)/page";
    page: "/__spa-preload";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "(public)/layout": typeof import("./app/(public)/layout.tsx");
  "(public)/(index)/page": typeof import("./app/(public)/(index)/page.tsx");
  "(public)/(get-involved)/page": typeof import("./app/(public)/(get-involved)/page.tsx");
  "(public)/(frequently-asked-questions)/page": typeof import("./app/(public)/(frequently-asked-questions)/page.tsx");
  "(public)/(latest-updates)/page": typeof import("./app/(public)/(latest-updates)/page.tsx");
  "(public)/(game-worlds)/(index)/page": typeof import("./app/(public)/(game-worlds)/(index)/page.tsx");
  "(public)/(game-worlds)/(create)/page": typeof import("./app/(public)/(game-worlds)/(create)/page.tsx");
  "(public)/(game-worlds)/(import)/page": typeof import("./app/(public)/(game-worlds)/(import)/page.tsx");
  "(public)/(not-found)/page": typeof import("./app/(public)/(not-found)/page.tsx");
  "(game)/(not-allowed)/page": typeof import("./app/(game)/(not-allowed)/page.tsx");
  "(game)/(not-found)/page": typeof import("./app/(game)/(not-found)/page.tsx");
  "(game)/(village-slug)/page": typeof import("./app/(game)/(village-slug)/page.tsx");
  "(game)/layout": typeof import("./app/(game)/layout.tsx");
  "(game)/(village-slug)/layout": typeof import("./app/(game)/(village-slug)/layout.tsx");
  "resources-page": typeof import("./app/(game)/(village-slug)/(village)/page.tsx");
  "village-page": typeof import("./app/(game)/(village-slug)/(village)/page.tsx");
  "(game)/(village-slug)/(map)/page": typeof import("./app/(game)/(village-slug)/(map)/page.tsx");
  "(game)/(village-slug)/fixed-width-layout": typeof import("./app/(game)/(village-slug)/fixed-width-layout.tsx");
  "resource-building-field-id-page": typeof import("./app/(game)/(village-slug)/(village)/(...building-field-id)/page.tsx");
  "village-building-field-id-page": typeof import("./app/(game)/(village-slug)/(village)/(...building-field-id)/page.tsx");
  "(game)/(village-slug)/(production-overview)/page": typeof import("./app/(game)/(village-slug)/(production-overview)/page.tsx");
  "(game)/(village-slug)/(hero)/page": typeof import("./app/(game)/(village-slug)/(hero)/page.tsx");
  "(game)/(village-slug)/(preferences)/page": typeof import("./app/(game)/(village-slug)/(preferences)/page.tsx");
  "(game)/(village-slug)/(statistics)/page": typeof import("./app/(game)/(village-slug)/(statistics)/page.tsx");
  "(game)/(village-slug)/(overview)/page": typeof import("./app/(game)/(village-slug)/(overview)/page.tsx");
  "(game)/(village-slug)/(quests)/page": typeof import("./app/(game)/(village-slug)/(quests)/page.tsx");
  "(game)/(village-slug)/(reports)/page": typeof import("./app/(game)/(village-slug)/(reports)/page.tsx");
  "(game)/(village-slug)/(reports)/(...report-id)/page": typeof import("./app/(game)/(village-slug)/(reports)/(...report-id)/page.tsx");
  "(game)/(village-slug)/(oasis-bonus-finder)/page": typeof import("./app/(game)/(village-slug)/(oasis-bonus-finder)/page.tsx");
  "(game)/(village-slug)/(players)/page": typeof import("./app/(game)/(village-slug)/(players)/page.tsx");
  "(game)/(village-slug)/(players)/(...player-slug)/page": typeof import("./app/(game)/(village-slug)/(players)/(...player-slug)/page.tsx");
  "(internal)/(spa-preload)/page": typeof import("./app/(internal)/(spa-preload)/page.tsx");
};