import type { HeroItem } from '@pillage-first/types/models/hero-item';

// ============================================================================
// HELMETS â€” IDs 1-15 (imageIds 1-15)
// ============================================================================
const helmets: HeroItem[] = [
  // --- Experience ---
  {
    id: 1,
    imageId: 1,
    name: 'HELMET_OF_AWARENESS',
    displayName: 'Helmet of Awareness',
    description: '+15% experience gain',
    slot: 'head',
    tier: 1,
    rarity: 'common',
    category: 'helmet',
    tribe: 'any',
    basePrice: 100,
    heroBonus: [{ attribute: 'experience', value: 15 }],
  },
  {
    id: 2,
    imageId: 2,
    name: 'HELMET_OF_ENLIGHTENMENT',
    displayName: 'Helmet of Enlightenment',
    description: '+20% experience gain',
    slot: 'head',
    tier: 2,
    rarity: 'uncommon',
    category: 'helmet',
    tribe: 'any',
    basePrice: 500,
    heroBonus: [{ attribute: 'experience', value: 20 }],
  },
  {
    id: 3,
    imageId: 3,
    name: 'HELMET_OF_WISDOM',
    displayName: 'Helmet of Wisdom',
    description: '+25% experience gain',
    slot: 'head',
    tier: 3,
    rarity: 'rare',
    category: 'helmet',
    tribe: 'any',
    basePrice: 2000,
    heroBonus: [{ attribute: 'experience', value: 25 }],
  },
  // --- HP Regen ---
  {
    id: 4,
    imageId: 4,
    name: 'HELMET_OF_REGENERATION',
    displayName: 'Helmet of Regeneration',
    description: '+10 HP regeneration/day',
    slot: 'head',
    tier: 1,
    rarity: 'common',
    category: 'helmet',
    tribe: 'any',
    basePrice: 100,
    heroBonus: [{ attribute: 'health', value: 10 }],
  },
  {
    id: 5,
    imageId: 5,
    name: 'HELMET_OF_HEALTH',
    displayName: 'Helmet of Health',
    description: '+15 HP regeneration/day',
    slot: 'head',
    tier: 2,
    rarity: 'uncommon',
    category: 'helmet',
    tribe: 'any',
    basePrice: 500,
    heroBonus: [{ attribute: 'health', value: 15 }],
  },
  {
    id: 6,
    imageId: 6,
    name: 'HELMET_OF_HEALING',
    displayName: 'Helmet of Healing',
    description: '+20 HP regeneration/day',
    slot: 'head',
    tier: 3,
    rarity: 'rare',
    category: 'helmet',
    tribe: 'any',
    basePrice: 2000,
    heroBonus: [{ attribute: 'health', value: 20 }],
  },
  // --- Culture Points ---
  {
    id: 7,
    imageId: 7,
    name: 'HELMET_OF_THE_GLADIATOR',
    displayName: 'Helmet of the Gladiator',
    description: '+100 CP/day',
    slot: 'head',
    tier: 1,
    rarity: 'common',
    category: 'helmet',
    tribe: 'any',
    basePrice: 100,
    heroBonus: [{ attribute: 'culturePoints', value: 100 }],
  },
  {
    id: 8,
    imageId: 8,
    name: 'HELMET_OF_THE_TRIBUNE',
    displayName: 'Helmet of the Tribune',
    description: '+400 CP/day',
    slot: 'head',
    tier: 2,
    rarity: 'uncommon',
    category: 'helmet',
    tribe: 'any',
    basePrice: 500,
    heroBonus: [{ attribute: 'culturePoints', value: 400 }],
  },
  {
    id: 9,
    imageId: 9,
    name: 'HELMET_OF_THE_CONSUL',
    displayName: 'Helmet of the Consul',
    description: '+1600 CP/day',
    slot: 'head',
    tier: 3,
    rarity: 'rare',
    category: 'helmet',
    tribe: 'any',
    basePrice: 2000,
    heroBonus: [{ attribute: 'culturePoints', value: 1600 }],
  },
  // --- Cavalry Training ---
  {
    id: 10,
    imageId: 10,
    name: 'HELMET_OF_THE_HORSEMAN',
    displayName: 'Helmet of the Horseman',
    description: '+10% cavalry training speed',
    slot: 'head',
    tier: 1,
    rarity: 'common',
    category: 'helmet',
    tribe: 'any',
    basePrice: 100,
    heroBonus: [{ attribute: 'cavalryTraining', value: 10 }],
  },
  {
    id: 11,
    imageId: 11,
    name: 'HELMET_OF_THE_CAVALRY',
    displayName: 'Helmet of the Cavalry',
    description: '+15% cavalry training speed',
    slot: 'head',
    tier: 2,
    rarity: 'uncommon',
    category: 'helmet',
    tribe: 'any',
    basePrice: 500,
    heroBonus: [{ attribute: 'cavalryTraining', value: 15 }],
  },
  {
    id: 12,
    imageId: 12,
    name: 'HELMET_OF_THE_HEAVY_CAVALRY',
    displayName: 'Helmet of the Heavy Cavalry',
    description: '+20% cavalry training speed',
    slot: 'head',
    tier: 3,
    rarity: 'rare',
    category: 'helmet',
    tribe: 'any',
    basePrice: 2000,
    heroBonus: [{ attribute: 'cavalryTraining', value: 20 }],
  },
  // --- Infantry Training ---
  {
    id: 13,
    imageId: 13,
    name: 'HELMET_OF_THE_MERCENARY',
    displayName: 'Helmet of the Mercenary',
    description: '+10% infantry training speed',
    slot: 'head',
    tier: 1,
    rarity: 'common',
    category: 'helmet',
    tribe: 'any',
    basePrice: 100,
    heroBonus: [{ attribute: 'infantryTraining', value: 10 }],
  },
  {
    id: 14,
    imageId: 14,
    name: 'HELMET_OF_THE_WARRIOR',
    displayName: 'Helmet of the Warrior',
    description: '+15% infantry training speed',
    slot: 'head',
    tier: 2,
    rarity: 'uncommon',
    category: 'helmet',
    tribe: 'any',
    basePrice: 500,
    heroBonus: [{ attribute: 'infantryTraining', value: 15 }],
  },
  {
    id: 15,
    imageId: 15,
    name: 'HELMET_OF_THE_ARCHON',
    displayName: 'Helmet of the Archon',
    description: '+20% infantry training speed',
    slot: 'head',
    tier: 3,
    rarity: 'rare',
    category: 'helmet',
    tribe: 'any',
    basePrice: 2000,
    heroBonus: [{ attribute: 'infantryTraining', value: 20 }],
  },
];

// ============================================================================
// Helper to generate tribe weapons. Pattern: 5 units أ— 3 tiers per tribe.
// ============================================================================
type WeaponUnit = {
  unitName: string;
  t1Atk: number;
  t2Atk: number;
  t3Atk: number;
  t1Name: string;
  t2Name: string;
  t3Name: string;
};

function generateTribeWeapons(
  tribe: HeroItem['tribe'],
  startId: number,
  units: WeaponUnit[],
): HeroItem[] {
  const result: HeroItem[] = [];
  const strengthByTier = [250, 1000, 4000] as const;
  const rarityByTier: HeroItem['rarity'][] = ['common', 'uncommon', 'rare'];
  const priceByTier = [100, 500, 2000];

  for (let unitIdx = 0; unitIdx < units.length; unitIdx++) {
    const unit = units[unitIdx];
    const tiers = [
      { name: unit.t1Name, atk: unit.t1Atk },
      { name: unit.t2Name, atk: unit.t2Atk },
      { name: unit.t3Name, atk: unit.t3Atk },
    ];
    for (let tierIdx = 0; tierIdx < 3; tierIdx++) {
      const tier = tiers[tierIdx];
      const idx = unitIdx * 3 + tierIdx;
      result.push({
        id: startId + idx,
        imageId: startId + idx,
        name: tier.name.toUpperCase().replace(/\s+/g, '_').replace(/'/g, ''),
        displayName: tier.name,
        description: `+${strengthByTier[tierIdx]} strength; +${tier.atk} atk/def per ${unit.unitName}`,
        slot: 'right-hand',
        tier: (tierIdx + 1) as HeroItem['tier'],
        rarity: rarityByTier[tierIdx],
        category: 'right-hand',
        tribe,
        basePrice: priceByTier[tierIdx],
        heroBonus: [
          { attribute: 'power', value: strengthByTier[tierIdx] },
          { attribute: 'unitAttack', value: tier.atk, unit: unit.unitName },
          { attribute: 'unitDefence', value: tier.atk, unit: unit.unitName },
        ],
      });
    }
  }
  return result;
}

// 16-30 Roman Weapons
const romanWeapons = generateTribeWeapons('romans', 16, [
  {
    unitName: 'Legionnaire',
    t1Atk: 3,
    t2Atk: 4,
    t3Atk: 5,
    t1Name: 'Short Sword of the Legionnaire',
    t2Name: 'Sword of the Legionnaire',
    t3Name: 'Long Sword of the Legionnaire',
  },
  {
    unitName: 'Praetorian',
    t1Atk: 3,
    t2Atk: 4,
    t3Atk: 5,
    t1Name: 'Short Sword of the Praetorian',
    t2Name: 'Sword of the Praetorian',
    t3Name: 'Long Sword of the Praetorian',
  },
  {
    unitName: 'Imperian',
    t1Atk: 3,
    t2Atk: 4,
    t3Atk: 5,
    t1Name: 'Short Sword of the Imperian',
    t2Name: 'Sword of the Imperian',
    t3Name: 'Long Sword of the Imperian',
  },
  {
    unitName: 'Imperatoris',
    t1Atk: 9,
    t2Atk: 12,
    t3Atk: 15,
    t1Name: 'Short Sword of the Imperatoris',
    t2Name: 'Sword of the Imperatoris',
    t3Name: 'Long Sword of the Imperatoris',
  },
  {
    unitName: 'Caesaris',
    t1Atk: 12,
    t2Atk: 16,
    t3Atk: 20,
    t1Name: 'Light Lance of the Caesaris',
    t2Name: 'Lance of the Caesaris',
    t3Name: 'Heavy Lance of the Caesaris',
  },
]);

// 31-45 Gaul Weapons
const gaulWeapons = generateTribeWeapons('gauls', 31, [
  {
    unitName: 'Phalanx',
    t1Atk: 3,
    t2Atk: 4,
    t3Atk: 5,
    t1Name: 'Spear of the Phalanx',
    t2Name: 'Pike of the Phalanx',
    t3Name: 'Lance of the Phalanx',
  },
  {
    unitName: 'Swordsman',
    t1Atk: 3,
    t2Atk: 4,
    t3Atk: 5,
    t1Name: 'Short Sword of the Swordsman',
    t2Name: 'Sword of the Swordsman',
    t3Name: 'Long Sword of the Swordsman',
  },
  {
    unitName: 'Theutates Thunder',
    t1Atk: 6,
    t2Atk: 8,
    t3Atk: 10,
    t1Name: 'Short Bow of the Theutates',
    t2Name: 'Bow of the Theutates',
    t3Name: 'Long Bow of the Theutates',
  },
  {
    unitName: 'Druidrider',
    t1Atk: 6,
    t2Atk: 8,
    t3Atk: 10,
    t1Name: 'Walking Staff of the Druidrider',
    t2Name: 'Staff of the Druidrider',
    t3Name: 'Fighting Staff of the Druidrider',
  },
  {
    unitName: 'Haeduan',
    t1Atk: 9,
    t2Atk: 12,
    t3Atk: 15,
    t1Name: 'Light Lance of the Haeduan',
    t2Name: 'Lance of the Haeduan',
    t3Name: 'Heavy Lance of the Haeduan',
  },
]);

// 46-60 Teuton Weapons
const teutonWeapons = generateTribeWeapons('teutons', 46, [
  {
    unitName: 'Clubswinger',
    t1Atk: 3,
    t2Atk: 4,
    t3Atk: 5,
    t1Name: 'Club of the Clubswinger',
    t2Name: 'Mace of the Clubswinger',
    t3Name: 'Morning Star of the Clubswinger',
  },
  {
    unitName: 'Spearman',
    t1Atk: 3,
    t2Atk: 4,
    t3Atk: 5,
    t1Name: 'Spear of the Spearman',
    t2Name: 'Pike of the Spearman',
    t3Name: 'Lance of the Spearman',
  },
  {
    unitName: 'Axeman',
    t1Atk: 3,
    t2Atk: 4,
    t3Atk: 5,
    t1Name: 'Hatchet of the Axeman',
    t2Name: 'Axe of the Axeman',
    t3Name: 'Battle Axe of the Axeman',
  },
  {
    unitName: 'Paladin',
    t1Atk: 6,
    t2Atk: 8,
    t3Atk: 10,
    t1Name: 'Light Hammer of the Paladin',
    t2Name: 'Hammer of the Paladin',
    t3Name: 'Heavy Hammer of the Paladin',
  },
  {
    unitName: 'Teutonic Knight',
    t1Atk: 9,
    t2Atk: 12,
    t3Atk: 15,
    t1Name: 'Short Sword of the Teutonic Knight',
    t2Name: 'Sword of the Teutonic Knight',
    t3Name: 'Long Sword of the Teutonic Knight',
  },
]);

// ============================================================================
// LEFT-HAND â€” IDs 61-81
// ============================================================================
const leftHandItems: HeroItem[] = [
  // --- Maps (61-63) ---
  {
    id: 61,
    imageId: 61,
    name: 'SMALL_MAP',
    displayName: 'Small Map',
    description: '30% faster return',
    slot: 'left-hand',
    tier: 1,
    rarity: 'common',
    category: 'left-hand',
    tribe: 'any',
    basePrice: 100,
    heroBonus: [{ attribute: 'returnSpeed', value: 30 }],
  },
  {
    id: 62,
    imageId: 62,
    name: 'MAP',
    displayName: 'Map',
    description: '40% faster return',
    slot: 'left-hand',
    tier: 2,
    rarity: 'uncommon',
    category: 'left-hand',
    tribe: 'any',
    basePrice: 500,
    heroBonus: [{ attribute: 'returnSpeed', value: 40 }],
  },
  {
    id: 63,
    imageId: 63,
    name: 'LARGE_MAP',
    displayName: 'Large Map',
    description: '50% faster return',
    slot: 'left-hand',
    tier: 3,
    rarity: 'rare',
    category: 'left-hand',
    tribe: 'any',
    basePrice: 2000,
    heroBonus: [{ attribute: 'returnSpeed', value: 50 }],
  },
  // --- Pennants (64-66) ---
  {
    id: 64,
    imageId: 64,
    name: 'SMALL_PENNANT',
    displayName: 'Small Pennant',
    description: '30% faster to own villages',
    slot: 'left-hand',
    tier: 1,
    rarity: 'common',
    category: 'left-hand',
    tribe: 'any',
    basePrice: 100,
    heroBonus: [{ attribute: 'ownVillageSpeed', value: 30 }],
  },
  {
    id: 65,
    imageId: 65,
    name: 'PENNANT',
    displayName: 'Pennant',
    description: '40% faster to own villages',
    slot: 'left-hand',
    tier: 2,
    rarity: 'uncommon',
    category: 'left-hand',
    tribe: 'any',
    basePrice: 500,
    heroBonus: [{ attribute: 'ownVillageSpeed', value: 40 }],
  },
  {
    id: 66,
    imageId: 66,
    name: 'GREAT_PENNANT',
    displayName: 'Great Pennant',
    description: '50% faster to own villages',
    slot: 'left-hand',
    tier: 3,
    rarity: 'rare',
    category: 'left-hand',
    tribe: 'any',
    basePrice: 2000,
    heroBonus: [{ attribute: 'ownVillageSpeed', value: 50 }],
  },
  // --- Standards (67-69) ---
  {
    id: 67,
    imageId: 67,
    name: 'SMALL_STANDARD',
    displayName: 'Small Standard',
    description: '15% faster to alliance members',
    slot: 'left-hand',
    tier: 1,
    rarity: 'common',
    category: 'left-hand',
    tribe: 'any',
    basePrice: 100,
    heroBonus: [{ attribute: 'allianceSpeed', value: 15 }],
  },
  {
    id: 68,
    imageId: 68,
    name: 'STANDARD',
    displayName: 'Standard',
    description: '20% faster to alliance members',
    slot: 'left-hand',
    tier: 2,
    rarity: 'uncommon',
    category: 'left-hand',
    tribe: 'any',
    basePrice: 500,
    heroBonus: [{ attribute: 'allianceSpeed', value: 20 }],
  },
  {
    id: 69,
    imageId: 69,
    name: 'GREAT_STANDARD',
    displayName: 'Great Standard',
    description: '25% faster to alliance members',
    slot: 'left-hand',
    tier: 3,
    rarity: 'rare',
    category: 'left-hand',
    tribe: 'any',
    basePrice: 2000,
    heroBonus: [{ attribute: 'allianceSpeed', value: 25 }],
  },
  // --- Thief Bags (73-75) ---
  {
    id: 73,
    imageId: 73,
    name: 'POUCH_OF_THE_THIEF',
    displayName: 'Pouch of the Thief',
    description: '10% cranny reduction',
    slot: 'left-hand',
    tier: 1,
    rarity: 'common',
    category: 'left-hand',
    tribe: 'any',
    basePrice: 100,
    heroBonus: [{ attribute: 'crannyReduction', value: 10 }],
  },
  {
    id: 74,
    imageId: 74,
    name: 'BAG_OF_THE_THIEF',
    displayName: 'Bag of the Thief',
    description: '15% cranny reduction',
    slot: 'left-hand',
    tier: 2,
    rarity: 'uncommon',
    category: 'left-hand',
    tribe: 'any',
    basePrice: 500,
    heroBonus: [{ attribute: 'crannyReduction', value: 15 }],
  },
  {
    id: 75,
    imageId: 75,
    name: 'SACK_OF_THE_THIEF',
    displayName: 'Sack of the Thief',
    description: '20% cranny reduction',
    slot: 'left-hand',
    tier: 3,
    rarity: 'rare',
    category: 'left-hand',
    tribe: 'any',
    basePrice: 2000,
    heroBonus: [{ attribute: 'crannyReduction', value: 20 }],
  },
  // --- Shields (76-78) ---
  {
    id: 76,
    imageId: 76,
    name: 'SMALL_SHIELD',
    displayName: 'Small Shield',
    description: '+250 fighting strength',
    slot: 'left-hand',
    tier: 1,
    rarity: 'common',
    category: 'left-hand',
    tribe: 'any',
    basePrice: 100,
    heroBonus: [{ attribute: 'power', value: 250 }],
  },
  {
    id: 77,
    imageId: 77,
    name: 'SHIELD',
    displayName: 'Shield',
    description: '+1000 fighting strength',
    slot: 'left-hand',
    tier: 2,
    rarity: 'uncommon',
    category: 'left-hand',
    tribe: 'any',
    basePrice: 500,
    heroBonus: [{ attribute: 'power', value: 1000 }],
  },
  {
    id: 78,
    imageId: 78,
    name: 'LARGE_SHIELD',
    displayName: 'Large Shield',
    description: '+4000 fighting strength',
    slot: 'left-hand',
    tier: 3,
    rarity: 'rare',
    category: 'left-hand',
    tribe: 'any',
    basePrice: 2000,
    heroBonus: [{ attribute: 'power', value: 4000 }],
  },
  // --- Horns (79-81) ---
  {
    id: 79,
    imageId: 79,
    name: 'SMALL_HORN_OF_THE_NATARIAN',
    displayName: 'Small Horn of the Natarian',
    description: '+20% attack vs. Natars',
    slot: 'left-hand',
    tier: 1,
    rarity: 'common',
    category: 'left-hand',
    tribe: 'any',
    basePrice: 100,
    heroBonus: [{ attribute: 'natarBonus', value: 20 }],
  },
  {
    id: 80,
    imageId: 80,
    name: 'HORN_OF_THE_NATARIAN',
    displayName: 'Horn of the Natarian',
    description: '+25% attack vs. Natars',
    slot: 'left-hand',
    tier: 2,
    rarity: 'uncommon',
    category: 'left-hand',
    tribe: 'any',
    basePrice: 500,
    heroBonus: [{ attribute: 'natarBonus', value: 25 }],
  },
  {
    id: 81,
    imageId: 81,
    name: 'GREAT_HORN_OF_THE_NATARIAN',
    displayName: 'Great Horn of the Natarian',
    description: '+30% attack vs. Natars',
    slot: 'left-hand',
    tier: 3,
    rarity: 'rare',
    category: 'left-hand',
    tribe: 'any',
    basePrice: 2000,
    heroBonus: [{ attribute: 'natarBonus', value: 30 }],
  },
];

// ============================================================================
// ARMOUR â€” IDs 82-93 (imageIds 82-93)
// ============================================================================
const armour: HeroItem[] = [
  // --- HP Regen ---
  {
    id: 82,
    imageId: 82,
    name: 'ARMOUR_OF_REGENERATION',
    displayName: 'Armor of Regeneration',
    description: '+20 HP/day',
    slot: 'torso',
    tier: 1,
    rarity: 'common',
    category: 'armour',
    tribe: 'any',
    basePrice: 100,
    heroBonus: [{ attribute: 'health', value: 20 }],
  },
  {
    id: 83,
    imageId: 83,
    name: 'ARMOUR_OF_HEALTH',
    displayName: 'Armor of Health',
    description: '+30 HP/day',
    slot: 'torso',
    tier: 2,
    rarity: 'uncommon',
    category: 'armour',
    tribe: 'any',
    basePrice: 500,
    heroBonus: [{ attribute: 'health', value: 30 }],
  },
  {
    id: 84,
    imageId: 84,
    name: 'ARMOUR_OF_HEALING',
    displayName: 'Armor of Healing',
    description: '+40 HP/day',
    slot: 'torso',
    tier: 3,
    rarity: 'rare',
    category: 'armour',
    tribe: 'any',
    basePrice: 2000,
    heroBonus: [{ attribute: 'health', value: 40 }],
  },
  // --- Damage Reduction + HP ---
  {
    id: 85,
    imageId: 85,
    name: 'LIGHT_SCALE_ARMOUR',
    displayName: 'Light Scale Armor',
    description: 'Damage âˆ’4 HP; +10 HP/day',
    slot: 'torso',
    tier: 1,
    rarity: 'common',
    category: 'armour',
    tribe: 'any',
    basePrice: 100,
    heroBonus: [
      { attribute: 'damageReduction', value: 4 },
      { attribute: 'health', value: 10 },
    ],
  },
  {
    id: 86,
    imageId: 86,
    name: 'SCALE_ARMOUR',
    displayName: 'Scale Armor',
    description: 'Damage âˆ’6 HP; +15 HP/day',
    slot: 'torso',
    tier: 2,
    rarity: 'uncommon',
    category: 'armour',
    tribe: 'any',
    basePrice: 500,
    heroBonus: [
      { attribute: 'damageReduction', value: 6 },
      { attribute: 'health', value: 15 },
    ],
  },
  {
    id: 87,
    imageId: 87,
    name: 'HEAVY_SCALE_ARMOUR',
    displayName: 'Heavy Scale Armor',
    description: 'Damage âˆ’8 HP; +20 HP/day',
    slot: 'torso',
    tier: 3,
    rarity: 'rare',
    category: 'armour',
    tribe: 'any',
    basePrice: 2000,
    heroBonus: [
      { attribute: 'damageReduction', value: 8 },
      { attribute: 'health', value: 20 },
    ],
  },
  // --- Fighting Strength ---
  {
    id: 88,
    imageId: 88,
    name: 'LIGHT_BREASTPLATE',
    displayName: 'Light Breastplate',
    description: '+250 fighting strength',
    slot: 'torso',
    tier: 1,
    rarity: 'common',
    category: 'armour',
    tribe: 'any',
    basePrice: 100,
    heroBonus: [{ attribute: 'power', value: 250 }],
  },
  {
    id: 89,
    imageId: 89,
    name: 'BREASTPLATE',
    displayName: 'Breastplate',
    description: '+1000 fighting strength',
    slot: 'torso',
    tier: 2,
    rarity: 'uncommon',
    category: 'armour',
    tribe: 'any',
    basePrice: 500,
    heroBonus: [{ attribute: 'power', value: 1000 }],
  },
  {
    id: 90,
    imageId: 90,
    name: 'HEAVY_BREASTPLATE',
    displayName: 'Heavy Breastplate',
    description: '+4000 fighting strength',
    slot: 'torso',
    tier: 3,
    rarity: 'rare',
    category: 'armour',
    tribe: 'any',
    basePrice: 2000,
    heroBonus: [{ attribute: 'power', value: 4000 }],
  },
  // --- Mixed: Damage Reduction + Strength ---
  {
    id: 91,
    imageId: 91,
    name: 'LIGHT_SEGMENTED_ARMOUR',
    displayName: 'Light Segmented Armor',
    description: 'Damage âˆ’3; +125 fighting strength',
    slot: 'torso',
    tier: 1,
    rarity: 'common',
    category: 'armour',
    tribe: 'any',
    basePrice: 100,
    heroBonus: [
      { attribute: 'damageReduction', value: 3 },
      { attribute: 'power', value: 125 },
    ],
  },
  {
    id: 92,
    imageId: 92,
    name: 'SEGMENTED_ARMOUR',
    displayName: 'Segmented Armor',
    description: 'Damage âˆ’4; +500 fighting strength',
    slot: 'torso',
    tier: 2,
    rarity: 'uncommon',
    category: 'armour',
    tribe: 'any',
    basePrice: 500,
    heroBonus: [
      { attribute: 'damageReduction', value: 4 },
      { attribute: 'power', value: 500 },
    ],
  },
  {
    id: 93,
    imageId: 93,
    name: 'HEAVY_SEGMENTED_ARMOUR',
    displayName: 'Heavy Segmented Armor',
    description: 'Damage âˆ’5; +2000 fighting strength',
    slot: 'torso',
    tier: 3,
    rarity: 'rare',
    category: 'armour',
    tribe: 'any',
    basePrice: 2000,
    heroBonus: [
      { attribute: 'damageReduction', value: 5 },
      { attribute: 'power', value: 2000 },
    ],
  },
];

// ============================================================================
// BOOTS â€” IDs 94-102 (imageIds 94-102)
// ============================================================================
const boots: HeroItem[] = [
  // --- HP Regen ---
  {
    id: 94,
    imageId: 94,
    name: 'BOOTS_OF_REGENERATION',
    displayName: 'Boots of Regeneration',
    description: '+10 HP/day',
    slot: 'boots',
    tier: 1,
    rarity: 'common',
    category: 'boots',
    tribe: 'any',
    basePrice: 100,
    heroBonus: [{ attribute: 'health', value: 10 }],
  },
  {
    id: 95,
    imageId: 95,
    name: 'BOOTS_OF_HEALTH',
    displayName: 'Boots of Health',
    description: '+15 HP/day',
    slot: 'boots',
    tier: 2,
    rarity: 'uncommon',
    category: 'boots',
    tribe: 'any',
    basePrice: 500,
    heroBonus: [{ attribute: 'health', value: 15 }],
  },
  {
    id: 96,
    imageId: 96,
    name: 'BOOTS_OF_HEALING',
    displayName: 'Boots of Healing',
    description: '+20 HP/day',
    slot: 'boots',
    tier: 3,
    rarity: 'rare',
    category: 'boots',
    tribe: 'any',
    basePrice: 2000,
    heroBonus: [{ attribute: 'health', value: 20 }],
  },
  // --- Troop Speed ---
  {
    id: 97,
    imageId: 97,
    name: 'BOOTS_OF_THE_MERCENARY',
    displayName: 'Boots of the Mercenary',
    description: '+25% troop speed after 20 fields',
    slot: 'boots',
    tier: 1,
    rarity: 'common',
    category: 'boots',
    tribe: 'any',
    basePrice: 100,
    heroBonus: [{ attribute: 'troopSpeed', value: 25 }],
  },
  {
    id: 98,
    imageId: 98,
    name: 'BOOTS_OF_THE_WARRIOR',
    displayName: 'Boots of the Warrior',
    description: '+50% troop speed after 20 fields',
    slot: 'boots',
    tier: 2,
    rarity: 'uncommon',
    category: 'boots',
    tribe: 'any',
    basePrice: 500,
    heroBonus: [{ attribute: 'troopSpeed', value: 50 }],
  },
  {
    id: 99,
    imageId: 99,
    name: 'BOOTS_OF_THE_ARCHON',
    displayName: 'Boots of the Archon',
    description: '+75% troop speed after 20 fields',
    slot: 'boots',
    tier: 3,
    rarity: 'rare',
    category: 'boots',
    tribe: 'any',
    basePrice: 2000,
    heroBonus: [{ attribute: 'troopSpeed', value: 75 }],
  },
  // --- Hero Speed (Spurs) ---
  {
    id: 100,
    imageId: 100,
    name: 'SMALL_SPURS',
    displayName: 'Small Spurs',
    description: '+3 fields/hour hero speed',
    slot: 'boots',
    tier: 1,
    rarity: 'common',
    category: 'boots',
    tribe: 'any',
    basePrice: 100,
    heroBonus: [{ attribute: 'heroSpeed', value: 3 }],
  },
  {
    id: 101,
    imageId: 101,
    name: 'SPURS',
    displayName: 'Spurs',
    description: '+4 fields/hour hero speed',
    slot: 'boots',
    tier: 2,
    rarity: 'uncommon',
    category: 'boots',
    tribe: 'any',
    basePrice: 500,
    heroBonus: [{ attribute: 'heroSpeed', value: 4 }],
  },
  {
    id: 102,
    imageId: 102,
    name: 'NASTY_SPURS',
    displayName: 'Nasty Spurs',
    description: '+5 fields/hour hero speed',
    slot: 'boots',
    tier: 3,
    rarity: 'rare',
    category: 'boots',
    tribe: 'any',
    basePrice: 2000,
    heroBonus: [{ attribute: 'heroSpeed', value: 5 }],
  },
];

// ============================================================================
// MOUNTS â€” IDs 103-105
// ============================================================================
const mounts: HeroItem[] = [
  {
    id: 103,
    imageId: 103,
    name: 'GELDING',
    displayName: 'Gelding',
    description: '14 fields/hour hero speed',
    slot: 'horse',
    tier: 1,
    rarity: 'common',
    category: 'horse',
    tribe: 'any',
    basePrice: 100,
    heroBonus: [{ attribute: 'speed', value: 14 }],
  },
  {
    id: 104,
    imageId: 104,
    name: 'THOROUGHBRED',
    displayName: 'Thoroughbred',
    description: '17 fields/hour hero speed',
    slot: 'horse',
    tier: 2,
    rarity: 'uncommon',
    category: 'horse',
    tribe: 'any',
    basePrice: 500,
    heroBonus: [{ attribute: 'speed', value: 17 }],
  },
  {
    id: 105,
    imageId: 105,
    name: 'WARHORSE',
    displayName: 'Warhorse',
    description: '20 fields/hour hero speed',
    slot: 'horse',
    tier: 3,
    rarity: 'rare',
    category: 'horse',
    tribe: 'any',
    basePrice: 2000,
    heroBonus: [{ attribute: 'speed', value: 20 }],
  },
];

// ============================================================================
// CONSUMABLES â€” IDs 106-114
// ============================================================================
const consumables: HeroItem[] = [
  {
    id: 106,
    imageId: 106,
    name: 'OINTMENT',
    displayName: 'Ointment',
    description: 'Restores 1% hero health per ointment',
    slot: 'consumable',
    rarity: 'common',
    category: 'consumable',
    tribe: 'any',
    basePrice: 5,
  },
  {
    id: 107,
    imageId: 107,
    name: 'SCROLL',
    displayName: 'Scroll',
    description: '+10 hero experience per scroll',
    slot: 'consumable',
    rarity: 'common',
    category: 'consumable',
    tribe: 'any',
    basePrice: 5,
  },
  {
    id: 108,
    imageId: 108,
    name: 'BUCKET',
    displayName: 'Bucket',
    description: 'Instantly revives dead hero',
    slot: 'consumable',
    rarity: 'rare',
    category: 'consumable',
    tribe: 'any',
    basePrice: 200,
  },
  {
    id: 109,
    imageId: 109,
    name: 'TABLET_OF_LAW',
    displayName: 'Tablet of Law',
    description: 'Increases village loyalty by 1%',
    slot: 'consumable',
    rarity: 'uncommon',
    category: 'consumable',
    tribe: 'any',
    basePrice: 50,
  },
  {
    id: 110,
    imageId: 110,
    name: 'BOOK_OF_WISDOM',
    displayName: 'Book of Wisdom',
    description: 'Resets all hero attribute points',
    slot: 'consumable',
    rarity: 'rare',
    category: 'consumable',
    tribe: 'any',
    basePrice: 100,
  },
  {
    id: 111,
    imageId: 111,
    name: 'ARTWORK',
    displayName: 'Artwork',
    description: 'Instantly grants Culture Points',
    slot: 'consumable',
    rarity: 'common',
    category: 'consumable',
    tribe: 'any',
    basePrice: null,
  },
  {
    id: 112,
    imageId: 112,
    name: 'SMALL_BANDAGES',
    displayName: 'Small Bandage',
    description: 'Heals up to 25% of battle losses',
    slot: 'consumable',
    rarity: 'common',
    category: 'consumable',
    tribe: 'any',
    basePrice: 20,
  },
  {
    id: 113,
    imageId: 113,
    name: 'BANDAGES',
    displayName: 'Bandage',
    description: 'Heals up to 33% of battle losses',
    slot: 'consumable',
    rarity: 'uncommon',
    category: 'consumable',
    tribe: 'any',
    basePrice: 40,
  },
  {
    id: 114,
    imageId: 114,
    name: 'CAGE',
    displayName: 'Cage',
    description: 'Capture animals from oasis without fighting',
    slot: 'consumable',
    rarity: 'common',
    category: 'consumable',
    tribe: 'any',
    basePrice: 20,
  },
];

// ============================================================================
// MORE WEAPONS: EGYPTIANS (115-129), HUNS (130-144), SPARTANS (149-163)
// ============================================================================
const egyptianWeapons = generateTribeWeapons('egyptians', 115, [
  {
    unitName: 'Slave Militia',
    t1Atk: 3,
    t2Atk: 4,
    t3Atk: 5,
    t1Name: 'Club of the Slave Militia',
    t2Name: 'Mace of the Slave Militia',
    t3Name: 'Morning Star of the Slave Militia',
  },
  {
    unitName: 'Ash Warden',
    t1Atk: 3,
    t2Atk: 4,
    t3Atk: 5,
    t1Name: 'Hatchet of the Ash Warden',
    t2Name: 'Axe of the Ash Warden',
    t3Name: 'Battle Axe of the Ash Warden',
  },
  {
    unitName: 'Khopesh Warrior',
    t1Atk: 3,
    t2Atk: 4,
    t3Atk: 5,
    t1Name: 'Short sword of the Khopesh Warrior',
    t2Name: 'Sword of the Khopesh Warrior',
    t3Name: 'Long sword of the Khopesh Warrior',
  },
  {
    unitName: 'Anhur Guard',
    t1Atk: 6,
    t2Atk: 8,
    t3Atk: 10,
    t1Name: 'Spear of the Anhur Guard',
    t2Name: 'Spike of the Anhur Guard',
    t3Name: 'Lance of the Anhur Guard',
  },
  {
    unitName: 'Resheph Chariot',
    t1Atk: 9,
    t2Atk: 12,
    t3Atk: 15,
    t1Name: 'Short bow of the Resheph Chariot',
    t2Name: 'Bow of the Resheph Chariot',
    t3Name: 'Longbow of the Resheph Chariot',
  },
]);

const hunWeapons = generateTribeWeapons('huns', 130, [
  {
    unitName: 'Mercenary',
    t1Atk: 3,
    t2Atk: 4,
    t3Atk: 5,
    t1Name: 'Hatchet of the Mercenary',
    t2Name: 'Axe of the Mercenary',
    t3Name: 'Battle Axe of the Mercenary',
  },
  {
    unitName: 'Bowman',
    t1Atk: 3,
    t2Atk: 4,
    t3Atk: 5,
    t1Name: 'Short bow of the Bowman',
    t2Name: 'Bow of the Bowman',
    t3Name: 'Longbow of the Bowman',
  },
  {
    unitName: 'Steppe Rider',
    t1Atk: 6,
    t2Atk: 8,
    t3Atk: 10,
    t1Name: 'Short sword of the Steppe Rider',
    t2Name: 'Sword of the Steppe Rider',
    t3Name: 'Long sword of the Steppe Rider',
  },
  {
    unitName: 'Marksman',
    t1Atk: 6,
    t2Atk: 8,
    t3Atk: 10,
    t1Name: 'Short bow of the Marksman',
    t2Name: 'Bow of the Marksman',
    t3Name: 'Longbow of the Marksman',
  },
  {
    unitName: 'Marauder',
    t1Atk: 9,
    t2Atk: 12,
    t3Atk: 15,
    t1Name: 'Short sword of the Marauder',
    t2Name: 'Sword of the Marauder',
    t3Name: 'Long sword of the Marauder',
  },
]);

// Note 145-148 are resources (145: Lumber, 146: Clay, etc.) which we skip.

const spartanWeapons = generateTribeWeapons('spartans', 149, [
  {
    unitName: 'Hoplite',
    t1Atk: 4,
    t2Atk: 6,
    t3Atk: 8,
    t1Name: 'Spear of the Hoplite',
    t2Name: 'Pike of the Hoplite',
    t3Name: 'Lance of the Hoplite',
  },
  {
    unitName: 'Shieldsman',
    t1Atk: 4,
    t2Atk: 6,
    t3Atk: 8,
    t1Name: 'Spear of the Shieldsman',
    t2Name: 'Pike of the Shieldsman',
    t3Name: 'Lance of the Shieldsman',
  },
  {
    unitName: 'Twinsteel Therion',
    t1Atk: 4,
    t2Atk: 6,
    t3Atk: 8,
    t1Name: 'Short sword of the Twinsteel Therion',
    t2Name: 'Sword of the Twinsteel Therion',
    t3Name: 'Long sword of the Twinsteel Therion',
  },
  {
    unitName: 'Elpida Rider',
    t1Atk: 8,
    t2Atk: 12,
    t3Atk: 16,
    t1Name: 'Short sword of the Elpida Rider',
    t2Name: 'Sword of the Elpida Rider',
    t3Name: 'Long sword of the Elpida Rider',
  },
  {
    unitName: 'Corinthian Crusher',
    t1Atk: 12,
    t2Atk: 18,
    t3Atk: 24,
    t1Name: 'Spear of the Corinthian Crusher',
    t2Name: 'Pike of the Corinthian Crusher',
    t3Name: 'Lance of the Corinthian Crusher',
  },
]);

// ============================================================================
// ARTIFACTS (kept for backward compat with world-items system)
// ============================================================================
export const artifacts: HeroItem[] = [];

// ============================================================================
// CONSTRUCTION PLANS (Phase 4 — World Wonder endgame)
// ============================================================================
export const constructionPlans: HeroItem[] = [
  {
    id: 200,
    imageId: 200,
    name: 'CONSTRUCTION_PLAN',
    displayName: 'Construction Plan',
    description:
      'A World Wonder Construction Plan. Required to start a World Wonder. Consumed when WW reaches Level 1.',
    slot: 'non-equipable',
    tier: 3,
    rarity: 'epic',
    category: 'construction_plan',
    tribe: 'any',
    basePrice: null,
    heroBonus: [],
  },
];

// ============================================================================
// EXPORTS
// ============================================================================

// ============================================================================
// VIKING WEAPONS (IDs 164-178)
// ============================================================================
const vikingWeapons: HeroItem[] = [
  {
    id: 164,
    imageId: 164,
    name: 'HATCHET_OF_THE_THRALL',
    displayName: 'Hatchet of the Thrall',
    description: 'Epic item with special bonuses',
    slot: 'right-hand',
    tier: 1,
    rarity: 'common',
    category: 'right-hand',
    tribe: 'vikings',
    basePrice: 100,
    heroBonus: [{ attribute: 'power', value: 250 }],
  },
  {
    id: 165,
    imageId: 165,
    name: 'AXE_OF_THE_THRALL',
    displayName: 'Axe of the Thrall',
    description: 'Epic item with special bonuses',
    slot: 'right-hand',
    tier: 2,
    rarity: 'uncommon',
    category: 'right-hand',
    tribe: 'vikings',
    basePrice: 500,
    heroBonus: [{ attribute: 'power', value: 250 }],
  },
  {
    id: 166,
    imageId: 166,
    name: 'BATTLE_AXE_OF_THE_THRALL',
    displayName: 'Battle Axe of the Thrall',
    description: 'Epic item with special bonuses',
    slot: 'right-hand',
    tier: 3,
    rarity: 'rare',
    category: 'right-hand',
    tribe: 'vikings',
    basePrice: 2000,
    heroBonus: [{ attribute: 'power', value: 250 }],
  },
  {
    id: 167,
    imageId: 167,
    name: 'SHORT_SWORD_OF_THE_SHIELD_MAIDEN',
    displayName: 'Short Sword of the Shield Maiden',
    description: 'Epic item with special bonuses',
    slot: 'right-hand',
    tier: 1,
    rarity: 'common',
    category: 'right-hand',
    tribe: 'vikings',
    basePrice: 100,
    heroBonus: [{ attribute: 'power', value: 250 }],
  },
  {
    id: 168,
    imageId: 168,
    name: 'SWORD_OF_THE_SHIELD_MAIDEN',
    displayName: 'Sword of the Shield Maiden',
    description: 'Epic item with special bonuses',
    slot: 'right-hand',
    tier: 2,
    rarity: 'uncommon',
    category: 'right-hand',
    tribe: 'vikings',
    basePrice: 500,
    heroBonus: [{ attribute: 'power', value: 250 }],
  },
  {
    id: 169,
    imageId: 169,
    name: 'LONG_SWORD_OF_THE_SHIELD_MAIDEN',
    displayName: 'Long Sword of the Shield Maiden',
    description: 'Epic item with special bonuses',
    slot: 'right-hand',
    tier: 3,
    rarity: 'rare',
    category: 'right-hand',
    tribe: 'vikings',
    basePrice: 2000,
    heroBonus: [{ attribute: 'power', value: 250 }],
  },
  {
    id: 170,
    imageId: 170,
    name: 'HATCHET_OF_THE_BERSERKER',
    displayName: 'Hatchet of the Berserker',
    description: 'Epic item with special bonuses',
    slot: 'right-hand',
    tier: 1,
    rarity: 'common',
    category: 'right-hand',
    tribe: 'vikings',
    basePrice: 100,
    heroBonus: [{ attribute: 'power', value: 250 }],
  },
  {
    id: 171,
    imageId: 171,
    name: 'AXE_OF_THE_BERSERKER',
    displayName: 'Axe of the Berserker',
    description: 'Epic item with special bonuses',
    slot: 'right-hand',
    tier: 2,
    rarity: 'uncommon',
    category: 'right-hand',
    tribe: 'vikings',
    basePrice: 500,
    heroBonus: [{ attribute: 'power', value: 250 }],
  },
  {
    id: 172,
    imageId: 172,
    name: 'BATTLE_AXE_OF_THE_BERSERKER',
    displayName: 'Battle Axe of the Berserker',
    description: 'Epic item with special bonuses',
    slot: 'right-hand',
    tier: 3,
    rarity: 'rare',
    category: 'right-hand',
    tribe: 'vikings',
    basePrice: 2000,
    heroBonus: [{ attribute: 'power', value: 250 }],
  },
  {
    id: 173,
    imageId: 173,
    name: 'SPEAR_OF_THE_HUSKARL_RIDERS',
    displayName: 'Spear of the Huskarl Riders',
    description: 'Epic item with special bonuses',
    slot: 'right-hand',
    tier: 1,
    rarity: 'common',
    category: 'right-hand',
    tribe: 'vikings',
    basePrice: 100,
    heroBonus: [{ attribute: 'power', value: 250 }],
  },
  {
    id: 174,
    imageId: 174,
    name: 'SPIKE_OF_THE_HUSKARL_RIDERS',
    displayName: 'Spike of the Huskarl Riders',
    description: 'Epic item with special bonuses',
    slot: 'right-hand',
    tier: 2,
    rarity: 'uncommon',
    category: 'right-hand',
    tribe: 'vikings',
    basePrice: 500,
    heroBonus: [{ attribute: 'power', value: 250 }],
  },
  {
    id: 175,
    imageId: 175,
    name: 'LANCE_OF_THE_HUSKARL_RIDERS',
    displayName: 'Lance of the Huskarl Riders',
    description: 'Epic item with special bonuses',
    slot: 'right-hand',
    tier: 3,
    rarity: 'rare',
    category: 'right-hand',
    tribe: 'vikings',
    basePrice: 2000,
    heroBonus: [{ attribute: 'power', value: 250 }],
  },
  {
    id: 176,
    imageId: 176,
    name: 'SHORT_SWORD_OF_THE_VALKYRIE_S_BLESSING',
    displayName: "Short Sword of the Valkyrie's Blessing",
    description: 'Epic item with special bonuses',
    slot: 'right-hand',
    tier: 1,
    rarity: 'common',
    category: 'right-hand',
    tribe: 'vikings',
    basePrice: 100,
    heroBonus: [{ attribute: 'power', value: 250 }],
  },
  {
    id: 177,
    imageId: 177,
    name: 'SWORD_OF_THE_VALKYRIE_S_BLESSING',
    displayName: "Sword of the Valkyrie's Blessing",
    description: 'Epic item with special bonuses',
    slot: 'right-hand',
    tier: 2,
    rarity: 'uncommon',
    category: 'right-hand',
    tribe: 'vikings',
    basePrice: 500,
    heroBonus: [{ attribute: 'power', value: 250 }],
  },
  {
    id: 178,
    imageId: 178,
    name: 'LONG_SWORD_OF_THE_VALKYRIE_S_BLESSING',
    displayName: "Long Sword of the Valkyrie's Blessing",
    description: 'Epic item with special bonuses',
    slot: 'right-hand',
    tier: 3,
    rarity: 'rare',
    category: 'right-hand',
    tribe: 'vikings',
    basePrice: 2000,
    heroBonus: [{ attribute: 'power', value: 250 }],
  },
];

export const items: HeroItem[] = [
  ...helmets, // 1-15
  ...romanWeapons, // 16-30
  ...gaulWeapons, // 31-45
  ...teutonWeapons, // 46-60
  ...leftHandItems, // 61-81
  ...armour, // 82-93
  ...boots, // 94-102
  ...mounts, // 103-105
  ...consumables, // 106-114
  ...egyptianWeapons, // 115-129
  ...hunWeapons, // 130-144
  ...spartanWeapons, // 149-163
  ...vikingWeapons,
  ...constructionPlans, // 200
];

// Use this for faster lookups
export const itemsMap = new Map<HeroItem['id'], HeroItem>(
  items.map((heroItem) => [heroItem.id, heroItem]),
);

// Helper: get items by category
export const getItemsByCategory = (category: HeroItem['category']) =>
  items.filter((i) => i.category === category);

// Helper: get items by tribe (for weapons)
export const getItemsByTribe = (tribe: HeroItem['tribe']) =>
  items.filter((i) => i.tribe === tribe);

// Helper: get items grouped by category
export const itemCategories = [
  'helmet',
  'armour',
  'boots',
  'left-hand',
  'right-hand',
  'horse',
  'consumable',
  'construction_plan',
] as const;

export const categoryDisplayNames: Record<string, string> = {
  helmet: 'Helmets',
  armour: 'Armor',
  boots: 'Boots',
  'left-hand': 'Left-Hand Items',
  'right-hand': 'Weapons',
  horse: 'Mounts',
  consumable: 'Consumables',
  construction_plan: 'Construction Plans',
};
