import type { Tribe } from '@pillage-first/types/models/tribe';

export const TRIBE_ID_TO_SLUG: Record<number, Tribe> = {
  1: 'romans',
  2: 'teutons',
  3: 'gauls',
  4: 'nature',
  5: 'natars',
  6: 'egyptians',
  7: 'huns',
  8: 'spartans',
};

export const TRIBE_UNITS: Record<Tribe, string[]> = {
  romans: [
    'LEGIONNAIRE',
    'PRAETORIAN',
    'IMPERIAN',
    'ROMAN_SCOUT',
    'EQUITES_IMPERATORIS',
    'EQUITES_CAESARIS',
    'ROMAN_RAM',
    'ROMAN_CATAPULT',
    'ROMAN_CHIEF',
    'ROMAN_SETTLER',
    'HERO',
  ],
  teutons: [
    'CLUBSWINGER',
    'SPEARMAN',
    'AXEMAN',
    'TEUTONIC_SCOUT',
    'PALADIN',
    'TEUTONIC_KNIGHT',
    'TEUTONIC_RAM',
    'TEUTONIC_CATAPULT',
    'TEUTONIC_CHIEF',
    'TEUTONIC_SETTLER',
    'HERO',
  ],
  gauls: [
    'PHALANX',
    'SWORDSMAN',
    'GAUL_SCOUT',
    'THEUTATES_THUNDER',
    'DRUIDRIDER',
    'HAEDUAN',
    'GAUL_RAM',
    'GAUL_CATAPULT',
    'GAUL_CHIEF',
    'GAUL_SETTLER',
    'HERO',
  ],
  egyptians: [
    'SLAVE_MILITIA',
    'ASH_WARDEN',
    'KHOPESH_WARRIOR',
    'EGYPTIAN_SCOUT',
    'ANHUR_GUARD',
    'RESHEPH_CHARIOT',
    'EGYPTIAN_RAM',
    'EGYPTIAN_CATAPULT',
    'EGYPTIAN_CHIEF',
    'EGYPTIAN_SETTLER',
    'HERO',
  ],
  huns: [
    'MERCENARY',
    'BOWMAN',
    'HUN_SCOUT',
    'STEPPE_RIDER',
    'MARKSMAN',
    'MARAUDER',
    'HUN_RAM',
    'HUN_CATAPULT',
    'HUN_CHIEF',
    'HUN_SETTLER',
    'HERO',
  ],
  spartans: [
    'HOPLITE',
    'SHIELDSMAN',
    'TWINSTEEL_THERION',
    'ELPIDA_RIDER',
    'CORINTHIAN_CRUSHER',
    'SPARTAN_SCOUT',
    'SPARTAN_RAM',
    'SPARTAN_CATAPULT',
    'SPARTAN_CHIEF',
    'SPARTAN_SETTLER',
    'HERO',
  ],
  nature: [
    'RAT',
    'SPIDER',
    'SERPENT',
    'BAT',
    'WILD_BOAR',
    'WOLF',
    'BEAR',
    'CROCODILE',
    'TIGER',
    'ELEPHANT',
  ],
  natars: [
    'PIKEMAN',
    'THORNED_WARRIOR',
    'GUARDSMAN',
    'NATARIAN_SCOUT',
    'AXERIDER',
    'NATARIAN_KNIGHT',
    'NATARIAN_RAM',
    'NATARIAN_CATAPULT',
    'NATARIAN_CHIEF',
    'NATARIAN_SETTLER',
  ],
};
